services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - apps/api/.env
    command: npm run dev
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/web/.env.docker
    command: npm run dev
    restart: unless-stopped
